// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ARUMcAuz22d9n7KfPOIN3MqRJ2VZAHg',
    appId: '1:226266704285:web:95653af663454bddb66774',
    messagingSenderId: '226266704285',
    projectId: 'fluttertestproject-1a42f',
    authDomain: 'fluttertestproject-1a42f.firebaseapp.com',
    storageBucket: 'fluttertestproject-1a42f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0-MscLskshQrfqavuwnA6bHF5d74zyts',
    appId: '1:226266704285:android:f2ff581e0862af58b66774',
    messagingSenderId: '226266704285',
    projectId: 'fluttertestproject-1a42f',
    storageBucket: 'fluttertestproject-1a42f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv3cZHyPHUbcreAfn7E9Nkw27OAErf0RI',
    appId: '1:226266704285:ios:693d46ffd78ad8bdb66774',
    messagingSenderId: '226266704285',
    projectId: 'fluttertestproject-1a42f',
    storageBucket: 'fluttertestproject-1a42f.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv3cZHyPHUbcreAfn7E9Nkw27OAErf0RI',
    appId: '1:226266704285:ios:693d46ffd78ad8bdb66774',
    messagingSenderId: '226266704285',
    projectId: 'fluttertestproject-1a42f',
    storageBucket: 'fluttertestproject-1a42f.firebasestorage.app',
    iosBundleId: 'com.example.flutterDemoUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ARUMcAuz22d9n7KfPOIN3MqRJ2VZAHg',
    appId: '1:226266704285:web:8a2461bc1c0206c4b66774',
    messagingSenderId: '226266704285',
    projectId: 'fluttertestproject-1a42f',
    authDomain: 'fluttertestproject-1a42f.firebaseapp.com',
    storageBucket: 'fluttertestproject-1a42f.firebasestorage.app',
  );

}